### ISSUE TITLE
Chapt 02. 常量部分 代码问题

### ISSUE THREAD

**Issue by Xrondev** [KeKe-Li/For-learning-Go-Tutorial#126]
LINK: https://github.com/KeKe-Li/For-learning-Go-Tutorial/blob/master/src/chapter02/01.0.md#%E5%B8%B8%E9%87%8F

常量部分

``` go
const x, y int = 1, 2 // 多常量初始化
const s = "Hello, KeKe!" // 类型推断
const ( // 常量组
a, b
c
= 10, 20
bool = false
)

func main() {

const m = "20"// 未使用用局部常量不会引发编译错误。
}
```

**常量组部分，代码是否有误？**

---
Env： **GO 1.19.2**（初学,不确定是不是新版本go语法规则更改），Windows10， Goland
Goland 报错：Line 6  Missing Value in the const declaration
运行时：
.\main.go:8:1: syntax error: unexpected =, expecting name

**Comment by KeKe-Li** [comment]
这个变量组，应该是上次修改，触碰了换行，已经更新 `a, b,c = 10, 20,30`
