### ISSUE TITLE
Golang GC 部分可以深入讲一下是如何扫描的。

### ISSUE THREAD

**Issue by tangrc99** [KeKe-Li/For-learning-Go-Tutorial#128]
讲 GC 的很多文章都没有清楚地说明，Golang 究竟是如何从栈上确认类型进行扫描的。如果能在文章中加入这一部分的内容，会对读者很有帮助！
这里有一篇博客文章，作者可以参考。https://www.jianshu.com/p/ebd8b012572e#

**Comment by KeKe-Li** [comment]
好的我后面找时间在写写，哈哈
